name: "Merge Environment Variables Action"
description: "Merges environment variables from multiple sources into a single source."
inputs:
  default_variables:
    description: "Default environment variables in INI format."
    required: true
  override_variables:
    description: "Override environment variables in INI format."
    required: true
  dynamic_variables:
    description: "Dynamic environment variables in INI format."
    required: true

outputs:
  merged_variables:
    description: "Merged environment variables in INI format."

runs:
  using: "node20"
  main: "dist/index.js"